version: '3.3'

services:
  mysql:
    image: mariadb:latest
    hostname: mysql
    environment:
      MYSQL_ROOT_PASSWORD: MyDBRoot123
      MYSQL_DATABASE: project
      MYSQL_USER: project
      MYSQL_PASSWORD: project
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - mynet

  myphp:
    image: ghcr.io/yokiiw/discussion-platform/myphp:latest
    hostname: myphp
    expose:
      - "9000"
    volumes:
      - ./demo:/var/www/html
    depends_on:
      - mysql
    networks:
      - mynet

  mynginx:
    image: nginx:latest
    hostname: mynginx
    ports:
      - "8080:80"
    volumes:
      - ./demo:/var/www/html
      - ./setup/nginx.ini:/etc/nginx/conf.d/default.conf
    depends_on:
      - myphp
    networks:
      - mynet

  phpMyAdmin:
    image: phpmyadmin/phpmyadmin:latest
    hostname: phpMyAdmin
    ports:
      - "8082:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: MyDBRoot123
      MYSQL_USER: project
      MYSQL_PASSWORD: project
    depends_on:
      - mysql
    networks:
      - mynet

volumes:
  demo:
    driver: local

networks:
  mynet:
    driver: overlay
    attachable: true
