FROM php:8.2-fpm

# Install MySQLi extension
RUN docker-php-ext-install mysqli

# Install libicu-dev package to resolve intl dependencies
RUN apt-get update && apt-get install -y libicu-dev

# Install intl extension
RUN docker-php-ext-install intl

# Ensure that the intl extension is properly configured and loaded every time PHP starts
RUN echo "extension=intl.so" > /usr/local/etc/php/conf.d/docker-php-ext-intl.ini

# Set working directory
WORKDIR /var/www/html
